{% set data = load_setup_py_data() %}

package:
  name: streamvis
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - streamvis = streamvis.cli:main

requirements:
  build:
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - numba
    - bokeh =2.1
    - jungfrau_utils =3
    - pyzmq
    - pillow >=4.3
    - colorcet
    - bottleneck
    - jinja2 <3.1  # TODO: bokeh/2.1.x breaks with jinja/3.1.0
    - cbor2

test:
  source_files:
    - tests
  requires:
    - pytest

about:
  home: https://github.com/paulscherrerinstitute/streamvis
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
